set(MEDIAN_CPU_DIR "${CMAKE_CURRENT_LIST_DIR}")
function(median_configure_cpu target)
  if(ENABLE_INTEL_SIMD)
    target_compile_definitions(${target} PRIVATE MEDIAN_ENABLE_SIMD=1)
    if(MSVC)
      set_source_files_properties("${MEDIAN_CPU_DIR}/simd_avx.cpp" PROPERTIES COMPILE_FLAGS "/arch:AVX")
      set_source_files_properties("${MEDIAN_CPU_DIR}/simd_avx2.cpp" PROPERTIES COMPILE_FLAGS "/arch:AVX2")
      set_source_files_properties("${MEDIAN_CPU_DIR}/simd_avx512.cpp" PROPERTIES COMPILE_FLAGS "/arch:AVX512")
      set_source_files_properties("${MEDIAN_CPU_DIR}/simd_fma3.cpp" "${MEDIAN_CPU_DIR}/simd_fma4.cpp" PROPERTIES COMPILE_FLAGS "/arch:AVX")
    else()
      set_source_files_properties("${MEDIAN_CPU_DIR}/simd_sse2.cpp" PROPERTIES COMPILE_FLAGS "-msse2")
      set_source_files_properties("${MEDIAN_CPU_DIR}/simd_sse41.cpp" PROPERTIES COMPILE_FLAGS "-msse4.1")
      set_source_files_properties("${MEDIAN_CPU_DIR}/simd_avx.cpp" PROPERTIES COMPILE_FLAGS "-mavx")
      set_source_files_properties("${MEDIAN_CPU_DIR}/simd_avx2.cpp" PROPERTIES COMPILE_FLAGS "-mavx2")
      set_source_files_properties("${MEDIAN_CPU_DIR}/simd_fma3.cpp" PROPERTIES COMPILE_FLAGS "-mavx -mfma")
      set_source_files_properties("${MEDIAN_CPU_DIR}/simd_fma4.cpp" PROPERTIES COMPILE_FLAGS "-mavx -mfma4 -mno-fma")
      set_source_files_properties("${MEDIAN_CPU_DIR}/simd_avx512.cpp" PROPERTIES COMPILE_FLAGS "-mavx512f -mavx512dq -mavx512bw -mavx512vl")
    endif()
  endif()
endfunction()
